//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusService.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color
        ///vilnius_bus_1,&quot;1&quot;,&quot;Stotis–Vikingų g.–Oro uostas&quot;,,3,https://www.stops.lt/vilnius/index.html#vilnius/bus/1,0073AC,FFFFFF
        ///vilnius_expressbus_1G,&quot;1G&quot;,&quot;Stotis–Kalvarijų g.–Santariškės&quot;,,3,https://www.stops.lt/vilnius/index.html#vilnius/expressbus/1G,008000,FFFFFF
        ///vilnius_bus_2,&quot;2&quot;,&quot;Stotis–Liepkalnio–Vikingų g.–Oro uostas&quot;,,3,https://www.stops.lt/vilnius/index.html#vilnius/bus/2,0073AC,FFFFFF
        ///vilnius_expressbus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string routes {
            get {
                return ResourceManager.GetString("routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type
        ///1,05:16:00,05:16:00,8262,1,0,0
        ///1,05:19:00,05:19:00,6650,2,0,0
        ///1,05:22:00,05:22:00,7851,3,0,0
        ///1,05:25:00,05:25:00,5173,4,0,0
        ///1,05:26:00,05:26:00,5175,5,0,0
        ///1,05:32:00,05:32:00,10359,6,0,0
        ///1,05:33:00,05:33:00,9738,7,0,0
        ///1,05:37:00,05:37:00,15589,8,0,0
        ///2,06:00:00,06:04:00,8262,1,0,0
        ///2,06:07:00,06:07:00,6650,2,0,0
        ///2,06:10:00,06:10:00,7851,3,0,0
        ///2,06:13:00,06:13:00,5173,4,0,0
        ///2,06:14:00,06:14:00,5175,5,0,0
        ///2,06:20:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stop_times {
            get {
                return ResourceManager.GetString("stop_times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,stop_url,location_type,parent_station
        ///9483,,&quot;1-asis Lentvaris&quot;,,54.64437,25.06552,https://www.stops.lt/vilnius/index.html#stop/3906,,
        ///9102,,&quot;Bijūnų st.&quot;,,54.66740,25.21588,https://www.stops.lt/vilnius/index.html#stop/1631,,
        ///16291,,&quot;Geležinio Vilko st.&quot;,,54.75762,25.27183,https://www.stops.lt/vilnius/index.html#stop/2145,,
        ///16295,,&quot;Geležinio Vilko st.&quot;,,54.75848,25.27229,https://www.stops.lt/vilnius/index.html#stop/2146,,
        ///8258,,&quot;Kaimelio žiedas&quot;,,54.7314 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stops {
            get {
                return ResourceManager.GetString("stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id,wheelchair_accessible
        ///vilnius_bus_1,12751,1,&quot;Oro uostas&quot;,,66888,vilnius_bus_1_a-b,1
        ///vilnius_bus_1,12751,2,&quot;Oro uostas&quot;,,66888,vilnius_bus_1_a-b,1
        ///vilnius_bus_1,12751,3,&quot;Oro uostas&quot;,,66889,vilnius_bus_1_a-b,1
        ///vilnius_bus_1,12751,4,&quot;Oro uostas&quot;,,66888,vilnius_bus_1_a-b,1
        ///vilnius_bus_1,12751,5,&quot;Oro uostas&quot;,,66889,vilnius_bus_1_a-b,1
        ///vilnius_bus_1,12751,6,&quot;Oro uostas&quot;,,66888,vilnius_bus_1_a-b,1
        ///vilnius_bus_1,12751,7,&quot;Oro uostas&quot;,,66 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trips {
            get {
                return ResourceManager.GetString("trips", resourceCulture);
            }
        }
    }
}
