//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissingPerson
    {
        public int Id { get; set; }
        public string faceToken { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string lastSeenDate { get; set; }
        public string lastSeenLocation { get; set; }
        public string Additional_Information { get; set; }
    }
}
