//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissingPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MissingPerson()
        {
            this.ContactPersons = new HashSet<ContactPerson>();
        }
    
        public int Id { get; set; }
        public string faceToken { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string lastSeenDate { get; set; }
        public string lastSeenLocation { get; set; }
        public string Additional_Information { get; set; }
        public string dateOfBirth { get; set; }
        public string faceImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactPerson> ContactPersons { get; set; }
    }
}
